.PHONY: clean All

All:
	@echo "----------Building project:[ method_address - Debug ]----------"
	@cd "method_address" && "$(MAKE)" -f  "method_address.mk"
clean:
	@echo "----------Cleaning project:[ method_address - Debug ]----------"
	@cd "method_address" && "$(MAKE)" -f  "method_address.mk" clean
